AWSTemplateFormatVersion: '2010-09-09'
Description: Tạo một EC2 instance đơn giản

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0c02fb55956c7d316  # Amazon Linux 2 AMI (x86_64) - thay đổi theo region
      InstanceType: t2.micro
      KeyName: my-keypair            # Thay bằng tên key pair có sẵn của bạn
      SecurityGroups:
        - !Ref InstanceSecurityGroup

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Cho phép SSH
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0  # Mở SSH toàn thế giới (không khuyến khích cho production)
